name: fMRI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.7
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - pip:
    - atlasreader
    - heudiconv==0.13.1
    - nibabel
    - niflow-nipype1-workflows
    - nilearn
    - nipy
    - nipype
    - nistats
    - pybids
    - plotly